// Vue/src/components/Experience.vue
<template>
  <div id="experience" class="p-5">
    <h2 className="mb-5">Experiencia</h2>
    <div v-for="experience in experiences" :key="experience.title">
      <h5>{{ experience.title }}</h5>
      <p>
        {{ experience.company }} - {{ experience.workday }} <br />
        <small>
          {{ experience.dates }} <br />
          {{ experience.location }} ({{ experience.modality }})
        </small>
      </p>
    </div>
  </div>
</template>

<script>
import data from "../assets/data.json";
export default {
  data() {
    return {
      experiences: data.experiences,
    };
  },
};
</script>

<style scoped>
h5,
p {
  padding-left: 5px;
  border-left: 2px solid blue;
}
</style>

// React/src/components/Experience.jsx
import styles from "../css/Experience.module.css";
import { useTranslation } from "react-i18next";

export default function Experience() {
  const lang = sessionStorage.getItem("lang");
  const { t } = useTranslation();
  const { experiences } = require(`../assets/data/data_${lang}.json`);

  return (
    <div id="experience" className="p-5 text-end">
      <h2 className="mb-5">{t("navbar.experience")}</h2>
      {experiences.map((experience) => (
        <div key={experience.title} className={styles.experience}>
          <h5 className={styles.dot}>{experience.title}</h5>
          <p>
            {experience.company} - {experience.workday} <br />
            <small>
              {experience.dates} <br />
              {experience.location} ({experience.modality})
            </small>
          </p>
        </div>
      ))}
    </div>
  );
}
