// Vue/src/components/Training.vue
<template>
  <div id="training" class="p-5">
    <h2 class="mb-5">Formación</h2>
    <div v-for="training in trainings" :key="training.title">
      <div>
        <h5>{{ training.title }}</h5>
        <p>
          {{ training.college }}
          <br />
          <small>
            {{ training.dates }}
            <br />
            {{ training.location }}
          </small>
        </p>
      </div>
    </div>
  </div>
</template>

<script>
import data from "../assets/data.json";
export default {
  data() {
    return {
      trainings: data.trainings,
    };
  },
};
</script>

<style scoped>
#training {
  background-color: #d0ccd0;
}
</style>

// React/src/components/Training.jsx
import styles from "../css/Training.module.css";
import { useTranslation } from "react-i18next";

export default function Training() {
  const lang = sessionStorage.getItem("lang");
  const { t } = useTranslation();
  const { trainings } = require(`../assets/data/data_${lang}.json`);

  return (
    <div id="training" className={"p-5 " + styles.trainings}>
      <h2 className="mb-5">{t("navbar.training")}</h2>
      {trainings.map((training) => (
        <div key={training.title} className={styles.training}>
          {/* <span className={styles.dot} /> */}
          <h5 className={styles.dot}>{training.title}</h5>
          <p>
            {training.college}
            <br />
            <small>
              {training.dates}
              <br />
              {training.location}
            </small>
          </p>
        </div>
      ))}
    </div>
  );
}
